language: c # defaults to ruby
install:
  - sudo apt-get install ksh zsh -y
before_script:
  - curl -o /tmp/urchin https://raw.githubusercontent.com/scraperwiki/urchin/master/urchin && chmod +x /tmp/urchin
script:
  - NVM_DIR=$TRAVIS_BUILD_DIR make SHELL=$SHELL TEST_SUITE=$TEST_SUITE URCHIN=/tmp/urchin test_shell
env:
  - SHELL=sh TEST_SUITE=fast
  - SHELL=dash TEST_SUITE=fast
  - SHELL=bash TEST_SUITE=fast
  - SHELL=zsh TEST_SUITE=fast
  - SHELL=ksh TEST_SUITE=fast
  - SHELL=sh TEST_SUITE=slow
