language: c # defaults to ruby
install:
  - sudo apt-get install ksh zsh -y
  - '[ -z "$WITHOUT_CURL" ] || sudo apt-get remove curl -y'
before_script:
  - '[ -n "$WITHOUT_CURL" ] || curl -o /tmp/urchin https://raw.githubusercontent.com/scraperwiki/urchin/master/urchin'
  - '[ -z "$WITHOUT_CURL" ] || wget -O /tmp/urchin https://raw.githubusercontent.com/scraperwiki/urchin/master/urchin'
  - chmod +x /tmp/urchin
script:
  - NVM_DIR=$TRAVIS_BUILD_DIR make TEST_SUITE=$TEST_SUITE URCHIN=/tmp/urchin $SHELL
env:
  - SHELL=sh TEST_SUITE=fast
  - SHELL=dash TEST_SUITE=fast
  - SHELL=bash TEST_SUITE=fast
  - SHELL=zsh TEST_SUITE=fast
  - SHELL=ksh TEST_SUITE=fast
  - SHELL=sh TEST_SUITE=slow
  - SHELL=dash TEST_SUITE=slow
  - SHELL=bash TEST_SUITE=slow
  - SHELL=zsh TEST_SUITE=slow
  - SHELL=ksh TEST_SUITE=slow
  - SHELL=sh TEST_SUITE=sourcing
  - SHELL=dash TEST_SUITE=sourcing
  - SHELL=bash TEST_SUITE=sourcing
  - SHELL=zsh TEST_SUITE=sourcing
  - SHELL=ksh TEST_SUITE=sourcing
  - SHELL=sh TEST_SUITE=installation
  - SHELL=sh TEST_SUITE=installation WITHOUT_CURL=1
  - SHELL=dash TEST_SUITE=installation
  - SHELL=dash TEST_SUITE=installation WITHOUT_CURL=1
  - SHELL=bash TEST_SUITE=installation
  - SHELL=bash TEST_SUITE=installation WITHOUT_CURL=1
  - SHELL=zsh TEST_SUITE=installation
  - SHELL=zsh TEST_SUITE=installation WITHOUT_CURL=1
  - SHELL=ksh TEST_SUITE=installation
  - SHELL=ksh TEST_SUITE=installation WITHOUT_CURL=1

