name: Automatic Rebase

on: [pull_request_target]

concurrency:
  group: rebase-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  _:
    name: "Automatic Rebase"

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6
      - uses: ljharb/rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
