name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -uses: action/setup-node@v2
       with:
         nod-version: 14
      -name: install deps
       run: npm ci
      -name: run tests
       run: npm test
